# Generated by Django 5.2.1 on 2025-06-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='song_images/'),
        ),
    ]
